# Streamlit secrets configuration
# For development use only - these will be configured in Streamlit Cloud dashboard

# This is a placeholder file. In Streamlit Cloud, set these as secrets.
# You can set environment variables in Streamlit Cloud's app settings.

[environment_variables]
# If you need to set a specific images path in cloud environment
# IMAGES_PATH = "your_cloud_images_path"
